version: '3.8'

services:
  # VaultIQ Web Application
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./uploads:/app/uploads  
      - ./search_cache:/app/search_cache
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=your-secret-key-here
    depends_on:
      - redis
    restart: unless-stopped

  # Redis for caching and task queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Celery worker for background tasks
  celery:
    build: .
    command: celery -A video_recall_project worker --loglevel=info
    volumes:
      - ./media:/app/media
      - ./uploads:/app/uploads
      - ./search_cache:/app/search_cache
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=your-secret-key-here
    depends_on:
      - redis
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/var/www/static:ro
      - ./media:/var/www/media:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  redis_data: 