# Generated by Django 4.2.23 on 2025-06-28 01:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_path', models.CharField(help_text='Path to the video file', max_length=500)),
                ('video_name', models.CharField(help_text='Original video filename', max_length=255)),
                ('youtube_url', models.URLField(blank=True, help_text='Original YouTube URL if this was a YouTube video', null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Video metadata', null=True)),
                ('transcription', models.JSONField(blank=True, help_text='Transcription results', null=True)),
                ('processing_errors', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='video_proce_status_bedb8c_idx'), models.Index(fields=['created_at'], name='video_proce_created_a43767_idx')],
            },
        ),
    ]
