# Generated by Django 4.2.23 on 2025-06-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Original YouTube URL if this was a YouTube video', null=True),
        ),
    ]
