# Generated by Django 4.2.23 on 2025-06-28 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("video_processor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="videojob",
            name="video_proce_status_bedb8c_idx",
        ),
        migrations.RemoveIndex(
            model_name="videojob",
            name="video_proce_created_a43767_idx",
        ),
        migrations.AddField(
            model_name="videojob",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="videojob",
            name="transcript",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="videojob",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="videojob",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="videojob",
            index=models.Index(
                fields=["user", "status"], name="video_proce_user_id_1e37ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videojob",
            index=models.Index(
                fields=["user", "created_at"], name="video_proce_user_id_8e6a8a_idx"
            ),
        ),
    ]
